kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.serviceName }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.diskSize }}
  hostPath:
    path: /data/mongo/
