---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
spec:
  selector:
    app: {{ .Values.serviceName }}-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.port }}
  type: LoadBalancer
